name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: newtestdemo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t newtestdemo.azurecr.io/myapp:${{ github.sha }}
        docker push newtestdemo.azurecr.io/myapp:${{ github.sha }}
    - name: deploy into azure funtions
      uses: Azure/functions-action@v1
      with:
        app-name: new-test-demo
        package: 'newtestdemo.azurecr.io/myapp:${{ github.sha }}'
        username: ${{ secrets.FUNCTIONS_USERNAME }}
        password: ${{ secrets.FUNCTIONS_PASSWORD }}
    - name: Azure logout
      run: |
        az logout
      
    